<template>
  <div class="blade-wrapper">
    <!-- Blade Panel -->
    <div class="blade-panel">
      <!-- Header -->
      <div class="blade-header">
        <div class="blade-header__left">
          <h2 class="blade-header__title">Subscribe to updates</h2>
        </div>
        <div class="blade-header__right">
          <button type="button" class="blade-header__close" aria-label="Close" @click="$emit('close')">
            <PendoIcon type="x" :size="16" />
          </button>
        </div>
      </div>

      <!-- Body -->
      <div class="blade-body">
        <!-- Success State: Show subscription card after successful confirmation -->
        <div v-if="isSubscribed" class="blade-content">
          <!-- Hero Description -->
          <div class="blade-section blade-hero">
            <h3 class="blade-hero__title">Subscribe to updates for {{ props.dashboardName || 'Autonomous Insights' }}</h3>
            <p class="blade-hero__description">Get recurring Slack updates with the latest dashboard metrics.</p>
          </div>

          <!-- Tabs -->
          <div class="blade-tabs">
            <div class="blade-tabs__links">
              <button type="button" :class="['blade-tabs__link', 'blade-tabs__link--active']">Schedule</button>
              <button type="button" :class="['blade-tabs__link']">Context</button>
            </div>
          </div>

          <!-- Subscription Card -->
          <div class="blade-section">
            <div class="subscription-card">
              <div class="subscription-card__header">
                <h4 class="subscription-card__title">{{ formData.name || props.dashboardName || 'Autonomous Insights' }}</h4>
                <button type="button" class="subscription-card__menu" aria-label="More options">
                  <PendoIcon type="more-horizontal-filled" :size="16" />
                </button>
              </div>
              <p class="subscription-card__details">
                {{ formData.frequency }} every {{ formData.day }} at {{ formData.time }} {{ formData.timezone }} in {{ formData.channels.join(', ') || '#channel' }}
              </p>
              <div class="subscription-card__status">
                <span 
                  class="status-indicator" 
                  :class="subscriptionStatus === 'active' ? 'status-indicator--active' : 'status-indicator--inactive'"
                ></span>
                <span class="status-text">{{ subscriptionStatus === 'active' ? 'Active' : 'Inactive' }}</span>
              </div>
            </div>
          </div>
        </div>

        <!-- Form State: Show form before confirmation -->
        <div v-else class="blade-content">
          <!-- Hero Description -->
          <div class="blade-section blade-hero">
            <h3 class="blade-hero__title">Subscribe to updates for {{ props.dashboardName || 'Autonomous Insights' }}</h3>
            <p class="blade-hero__description">Get recurring Slack updates with the latest dashboard metrics.</p>
          </div>

          <!-- Tabs -->
          <div class="blade-tabs">
            <div class="blade-tabs__links">
              <button
                type="button"
                :class="['blade-tabs__link', { 'blade-tabs__link--active': activeTab === 'scheduling' }]"
                @click="activeTab = 'scheduling'"
              >
                Schedule
              </button>
              <button
                type="button"
                :class="['blade-tabs__link', { 'blade-tabs__link--active': activeTab === 'context' }]"
                @click="activeTab = 'context'"
              >
                Context
              </button>
            </div>
          </div>

          <!-- Context Tab Content -->
          <div v-if="activeTab === 'context'" class="blade-tab-content">
            <div class="blade-section context-tracking-section">
              <div class="context-tracking-header">
                <h5 class="blade-label">Dashboard context</h5>
                <p class="blade-helper">This description is generated by Pendo AI based on your dashboard and event details. You can edit it.</p>
              </div>
              <div
                class="context-input-container"
                :class="{ 'context-input-container--edit': isEditMode }"
              >
                <div class="context-textarea-wrapper">
                  <textarea
                    v-model="contextDescription"
                    class="context-textarea pendo-dropdown-scroll"
                    :readonly="!isEditMode"
                  ></textarea>
                </div>
                <div v-if="contextAttachments.length > 0" class="context-attachments-row">
                  <p class="context-attachments-label">AI has access to:</p>
                  <div
                    v-for="(attachment, index) in displayedAttachments"
                    :key="attachment.name"
                    class="blade-tag"
                    :class="{ 'blade-tag--truncate': attachment.truncate }"
                  >
                    <PendoIcon :type="getAttachmentIcon(attachment.name)" :size="12" class="blade-tag__icon" />
                    <span class="blade-tag__text">{{ attachment.name }}</span>
                    <button
                      v-if="!attachment.isCounter"
                      type="button"
                      class="blade-tag__close"
                      aria-label="Remove attachment"
                      @click="removeContextAttachment(attachment.originalIndex)"
                    >
                      <PendoIcon type="x" :size="12" :stroke-width="2" />
                    </button>
                  </div>
                  <div v-if="remainingAttachmentsCount > 0" class="blade-tag blade-tag--counter">
                    <span class="blade-tag__text">+{{ remainingAttachmentsCount }}</span>
                  </div>
                </div>
                <div class="context-add-attachment-row">
                  <input
                    ref="contextFileInputRef"
                    type="file"
                    accept=".pdf,.docx,.txt,.png,.jpg,.jpeg,.svg,.xlsx,.csv"
                    class="hidden"
                    @change="handleContextFileSelect"
                  />
                  <PendoButton
                    type="secondary"
                    prefix-icon="plus"
                    label="Add attachment"
                    size="small"
                    @click="triggerContextFileInput"
                  />
                  <div class="context-edit-icons">
                    <button type="button" class="context-edit-icon" :aria-label="isEditMode ? 'Save' : 'Edit'" @click="toggleEditMode">
                      <PendoIcon :type="isEditMode ? 'check' : 'edit'" :size="16" />
                    </button>
                    <button type="button" class="context-edit-icon" aria-label="Undo" @click="undoChanges">
                      <PendoIcon type="rotate-ccw" :size="16" />
                    </button>
                  </div>
                </div>
              </div>
            </div>

            <div class="blade-section">
              <div class="blade-section-header">
                <h4 class="blade-label">Key events</h4>
                <p class="blade-helper">These event descriptions help generate more relevant summaries. They come from your event details and can be edited here.</p>
              </div>
              <div class="blade-field-group">
                <label class="blade-field-label">cardInsightsNavigation</label>
                <PendoInput
                  v-model="formData.keyEvents.cardInsightsNavigation"
                  placeholder="This feature measures clicks on Trend cards."
                  :readonly="true"
                />
              </div>
              <div class="blade-field-group">
                <label class="blade-field-label">trendsLoaded</label>
                <PendoInput
                  v-model="formData.keyEvents.trendsLoaded"
                  placeholder="Tracks when Trends are loaded in the UI."
                  :readonly="true"
                />
              </div>
            </div>
          </div>

          <!-- Scheduling Tab Content -->
          <div v-else-if="activeTab === 'scheduling'" class="blade-tab-content">
            <!-- Frequency -->
            <div class="blade-section">
              <h5 class="blade-label">Frequency</h5>
              <div class="blade-button-group">
                <button
                  type="button"
                  :class="['blade-button-group__item', { 'blade-button-group__item--active': formData.frequency === 'Daily' }]"
                  @click="formData.frequency = 'Daily'"
                >
                  Daily
                </button>
                <button
                  type="button"
                  :class="['blade-button-group__item', { 'blade-button-group__item--active': formData.frequency === 'Weekly' }]"
                  @click="formData.frequency = 'Weekly'"
                >
                  Weekly
                </button>
                <button
                  type="button"
                  :class="['blade-button-group__item', { 'blade-button-group__item--active': formData.frequency === 'Monthly' }]"
                  @click="formData.frequency = 'Monthly'"
                >
                  Monthly
                </button>
              </div>

              <!-- Day/Time/Timezone - Conditional based on frequency -->
              <!-- Daily: Time + Timezone -->
              <div v-if="formData.frequency === 'Daily'" class="blade-row">
                <div class="blade-field">
                  <label class="blade-field__label">Time</label>
                  <PendoSelect v-model="formData.time" :options="timeOptions" />
                </div>
                <div class="blade-field">
                  <label class="blade-field__label">Time zone</label>
                  <PendoSelect v-model="formData.timezone" :options="timezoneOptions" />
                </div>
              </div>

              <!-- Weekly: Day + Time + Timezone -->
              <div v-else-if="formData.frequency === 'Weekly'" class="blade-row">
                <div class="blade-field">
                  <label class="blade-field__label">Day</label>
                  <PendoSelect v-model="formData.day" :options="dayOptions" />
                </div>
                <div class="blade-field">
                  <label class="blade-field__label">Time</label>
                  <PendoSelect v-model="formData.time" :options="timeOptions" />
                </div>
                <div class="blade-field">
                  <label class="blade-field__label">Time zone</label>
                  <PendoSelect v-model="formData.timezone" :options="timezoneOptions" />
                </div>
              </div>

              <!-- Monthly: Day of month + Time + Timezone -->
              <div v-else-if="formData.frequency === 'Monthly'" class="blade-row">
                <div class="blade-field">
                  <label class="blade-field__label">Day of month</label>
                  <PendoSelect v-model="formData.dayOfMonth" :options="dayOfMonthOptions" />
                </div>
                <div class="blade-field">
                  <label class="blade-field__label">Time</label>
                  <PendoSelect v-model="formData.time" :options="timeOptions" />
                </div>
                <div class="blade-field">
                  <label class="blade-field__label">Time zone</label>
                  <PendoSelect v-model="formData.timezone" :options="timezoneOptions" />
                </div>
              </div>
            </div>

            <!-- Name -->
            <div class="blade-section">
              <h5 class="blade-label">Update name</h5>
              <PendoInput v-model="formData.name" placeholder="Weekly Trends insights digest" style="width: 100%;" />
              <p class="blade-helper" style="margin-top: 4px; font-size: 12.642px;">This name appears at the top of the Slack message.</p>
            </div>

            <!-- Subscription Type -->
            <div class="blade-section">
              <h5 class="blade-label">Send updates to</h5>
              <PendoSelect v-model="formData.subscriptionType" :options="subscriptionTypeOptions" />
            </div>

            <!-- Channels -->
            <div class="blade-section">
              <h5 class="blade-label">Channels</h5>
              
              <div class="blade-channel-wrapper">
                <div 
                  class="blade-channel-select" 
                  :class="{ 'blade-channel-select--open': showChannelDropdown }"
                  tabindex="0"
                  @click="toggleChannelDropdown"
                  @keydown.enter.prevent="toggleChannelDropdown"
                  @keydown.space.prevent="toggleChannelDropdown"
                  @keydown.esc="showChannelDropdown = false"
                >
                  <div v-if="formData.channels.length > 0" class="blade-channel-tags">
                    <div
                      v-for="(channel, index) in formData.channels"
                      :key="channel"
                      class="blade-tag"
                    >
                      <span class="blade-tag__text">{{ channel }}</span>
                      <button
                        type="button"
                        class="blade-tag__close"
                        aria-label="Remove channel"
                        @click.stop="removeChannel(index)"
                      >
                        <PendoIcon type="x" :size="12" :stroke-width="2" />
                      </button>
                    </div>
                  </div>
                  <span v-else class="blade-channel-select__placeholder">Select channels</span>
                  <div 
                    class="blade-channel-select__icon"
                    :class="{ 'blade-channel-select__icon--open': showChannelDropdown }"
                  >
                    <PendoIcon type="chevron-down" :size="16" />
                  </div>
                </div>
                
                <!-- Channel Dropdown -->
                <Transition name="channel-dropdown">
                  <div v-if="showChannelDropdown" class="blade-channel-dropdown pendo-dropdown-scroll">
                    <div
                      v-for="channel in availableChannels"
                      :key="channel"
                      class="blade-channel-dropdown__item"
                      @click="toggleChannel(channel)"
                    >
                      <span>{{ channel }}</span>
                      <PendoIcon v-if="formData.channels.includes(channel)" type="check" :size="16" />
                    </div>
                  </div>
                </Transition>
              </div>
            </div>

            <!-- Test -->
            <div class="blade-section">
              <h5 class="blade-sublabel">Send test message to</h5>
              
              <div class="blade-test-row">
                <PendoSelect
                  v-model="formData.testChannel"
                  :options="testChannelOptions"
                  placeholder="Select channel"
                  :open-upward="true"
                  class="blade-test-select"
                />
                <PendoButton
                  type="tertiary"
                  label="Send test"
                  suffix-icon="send"
                  size="small"
                  :disabled="!formData.testChannel"
                />
              </div>
            </div>

            <!-- Add Another Subscription -->
            <div class="blade-section blade-section--bottom">
              <PendoButton
                type="secondary"
                prefix-icon="plus"
                label="Add another"
                size="small"
              />
            </div>
          </div>

        </div>
      </div>

      <!-- Footer -->
      <div class="blade-footer">
        <!-- Success State Footer: Show "Add another subscription" button -->
        <div v-if="isSubscribed" class="blade-footer__actions blade-footer__actions--success">
          <PendoButton
            type="secondary"
            prefix-icon="plus"
            label="Add another"
            @click="resetForm"
          />
        </div>

        <!-- Form State Footer: Show Cancel and Confirm buttons -->
        <div v-else class="blade-footer__actions">
          <PendoButton
            type="secondary"
            label="Cancel"
            @click="$emit('close')"
          />
          <PendoButton
            type="primary"
            label="Subscribe"
            @click="handleConfirm"
          />
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { PendoButton, PendoInput, PendoSelect, PendoIcon } from './pendo'

const props = defineProps({
  dashboardName: {
    type: String,
    default: 'Dashboard'
  }
})

const emit = defineEmits(['close', 'save'])

const activeTab = ref('scheduling')
const showChannelDropdown = ref(false)
const isEditMode = ref(false)
const contextFileInputRef = ref(null)
const isSubscribed = ref(false) // Track if subscription card should show
const subscriptionStatus = ref('active') // Track status: 'active' or 'inactive'

const formData = ref({
  frequency: 'Weekly',
  day: 'Monday',
  dayOfMonth: '1',
  time: '9:00 AM',
  timezone: 'EST',
  name: props.dashboardName,
  subscriptionType: 'Slack',
  channels: [],
  testChannel: '',
  keyEvents: {
    cardInsightsNavigation: 'This feature measures clicks on Trend cards.',
    trendsLoaded: 'Tracks when Trends are loaded in the UI.'
  }
})

const contextDescription = ref(`This dashboard monitors the Trends launch—a feature that uses AI to automatically surface meaningful patterns, anomalies, and insights from product data, helping teams identify important changes without manual analysis.

You're measuring engagement (target: 50% of accounts taking Level 1 actions within the first month), interaction depth with card insights, adoption patterns, time to first engagement, user journey flows, and gathering qualitative feedback from in-app guides. Segments compare active users vs. non-users to validate whether Trends is reducing manual analysis time and improving signal detection.`)

const originalContextDescription = ref(contextDescription.value)
const contextAttachments = ref([])

const availableChannels = [
  '#n8n-test',
  '#product-team-updates',
  '#team-insights',
  '#engineering',
  '#design',
  '#customer-success',
  '#sales'
]

const testChannelOptions = computed(() => {
  return availableChannels.map(channel => ({
    value: channel,
    label: channel
  }))
})

// Computed properties for attachment display logic
const displayedAttachments = computed(() => {
  const count = contextAttachments.value.length
  
  if (count === 0) return []
  
  // Show 1 tag with full text
  if (count === 1) {
    return [{
      name: contextAttachments.value[0],
      originalIndex: 0,
      truncate: false,
      isCounter: false
    }]
  }
  
  // Show 2 tags with truncation
  if (count === 2) {
    return contextAttachments.value.map((attachment, index) => ({
      name: attachment,
      originalIndex: index,
      truncate: true,
      isCounter: false
    }))
  }
  
  // Show 2 truncated tags for 3+ attachments
  return contextAttachments.value.slice(0, 2).map((attachment, index) => ({
    name: attachment,
    originalIndex: index,
    truncate: true,
    isCounter: false
  }))
})

const remainingAttachmentsCount = computed(() => {
  const count = contextAttachments.value.length
  return count >= 3 ? count - 2 : 0
})

const dayOptions = [
  { value: 'Monday', label: 'Monday' },
  { value: 'Tuesday', label: 'Tuesday' },
  { value: 'Wednesday', label: 'Wednesday' },
  { value: 'Thursday', label: 'Thursday' },
  { value: 'Friday', label: 'Friday' },
  { value: 'Saturday', label: 'Saturday' },
  { value: 'Sunday', label: 'Sunday' }
]

const dayOfMonthOptions = Array.from({ length: 31 }, (_, i) => {
  const day = i + 1
  return { value: String(day), label: String(day) }
})

const timeOptions = [
  { value: '9:00 AM', label: '9:00 AM' },
  { value: '10:00 AM', label: '10:00 AM' },
  { value: '11:00 AM', label: '11:00 AM' },
  { value: '12:00 PM', label: '12:00 PM' }
]

const timezoneOptions = [
  { value: 'EST', label: 'EST' },
  { value: 'CST', label: 'CST' },
  { value: 'MST', label: 'MST' },
  { value: 'PST', label: 'PST' }
]

const subscriptionTypeOptions = [
  { value: 'Slack', label: 'Slack', icon: 'slack' },
  { value: 'Teams', label: 'Teams', icon: 'teams' },
  { value: 'Email', label: 'Email' }
]

const removeChannel = (index) => {
  formData.value.channels.splice(index, 1)
}

const toggleChannelDropdown = () => {
  showChannelDropdown.value = !showChannelDropdown.value
}

const toggleChannel = (channel) => {
  const index = formData.value.channels.indexOf(channel)
  if (index > -1) {
    formData.value.channels.splice(index, 1)
  } else {
    formData.value.channels.push(channel)
  }
}

// Context tab functions
const toggleEditMode = () => {
  if (isEditMode.value) {
    // Save changes when exiting edit mode
    originalContextDescription.value = contextDescription.value
  }
  isEditMode.value = !isEditMode.value
}

const undoChanges = () => {
  contextDescription.value = originalContextDescription.value
  isEditMode.value = false
}

const triggerContextFileInput = () => {
  contextFileInputRef.value?.click()
}

const handleContextFileSelect = (event) => {
  const files = event.target.files
  if (files && files.length > 0) {
    for (let i = 0; i < files.length; i++) {
      contextAttachments.value.push(files[i].name)
    }
    event.target.value = ''
  }
}

const removeContextAttachment = (index) => {
  contextAttachments.value.splice(index, 1)
}

const getAttachmentIcon = (filename) => {
  const ext = filename.toLowerCase().split('.').pop()
  if (['pdf', 'docx', 'txt'].includes(ext)) return 'file-text'
  if (['csv', 'xlsx'].includes(ext)) return 'table'
  if (['png', 'jpg', 'jpeg', 'svg'].includes(ext)) return 'image'
  return 'file'
}

const resetForm = () => {
  // Reset to form state to add another subscription
  isSubscribed.value = false
  subscriptionStatus.value = 'active'
  activeTab.value = 'scheduling'
  formData.value.channels = []
}

const handleConfirm = async () => {
  // Send confirmation to Slack via n8n webhook
  try {
    const webhookUrl = 'https://pendoio.app.n8n.cloud/webhook/dashboard-subscribe'
    
    const response = await fetch(webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        userName: 'Tiffany Kitchen',
        dashboardName: props.dashboardName || 'Autonomous Insights',
        dashboardUrl: `${window.location.origin}/insights/static-url`,
        prototypeUrl: window.location.origin,
        settingsUrl: `${window.location.origin}/settings`,
        // Include subscription details for Slack message
        name: formData.value.name,
        frequency: formData.value.frequency,
        day: formData.value.day,
        dayOfMonth: formData.value.dayOfMonth,
        time: formData.value.time,
        timezone: formData.value.timezone
      })
    })

    if (!response.ok) {
      throw new Error(`Webhook failed with status: ${response.status}`)
    }

    console.log('✅ Slack confirmation sent successfully')
    console.log('Subscription data:', formData.value)
    
    // Show subscription card with ACTIVE status
    isSubscribed.value = true
    subscriptionStatus.value = 'active'

    if (typeof pendo !== 'undefined') {
      pendo.track('blade_configuration_confirmed', {
        dashboardName: props.dashboardName,
        frequency: formData.value.frequency,
        day: formData.value.day,
        dayOfMonth: formData.value.dayOfMonth,
        time: formData.value.time,
        timezone: formData.value.timezone,
        channelCount: formData.value.channels.length,
        subscriptionStatus: 'active'
      })
    }

    // Emit save event if parent is listening
    emit('save', formData.value)
  } catch (error) {
    console.error('Failed to send Slack confirmation:', error)
    
    // Show alert to user
    alert('Subscription saved, but failed to send Slack confirmation. Please check the console for details.')
    
    // Show subscription card with INACTIVE status
    isSubscribed.value = true
    subscriptionStatus.value = 'inactive'
    
    // Still log the form data
    console.log('Subscription data:', formData.value)
  }
}

// Click outside handler to close dropdown
const handleClickOutside = (event) => {
  const wrapper = event.target.closest('.blade-channel-wrapper')
  if (!wrapper && showChannelDropdown.value) {
    showChannelDropdown.value = false
  }
}

onMounted(() => {
  document.addEventListener('click', handleClickOutside)
})

onUnmounted(() => {
  document.removeEventListener('click', handleClickOutside)
})
</script>

<style scoped>
.blade-wrapper {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  width: 600px;
  display: flex;
  flex-direction: column;
}

.blade-panel {
  background: var(--gray-0);
  border-left: 1px solid var(--gray-40);
  display: flex;
  flex-direction: column;
  height: 100%;
  width: 100%;
}

/* Header */
.blade-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 16px 20px 16px 24px;
  border-bottom: 1px solid var(--gray-40);
  background: var(--gray-0);
}

.blade-header__left {
  flex: 1;
  display: flex;
  align-items: center;
  gap: 8px;
}

.blade-header__title {
  font-family: 'Inter', sans-serif;
  font-weight: 600;
  font-size: 14.222px;
  line-height: 1.5;
  color: var(--gray-90);
  margin: 0;
}

.blade-header__right {
  display: flex;
  align-items: center;
  justify-content: flex-end;
  gap: 8px;
}

.blade-header__close {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 24px;
  height: 26px;
  padding: 0;
  background: none;
  border: none;
  border-radius: 3px;
  cursor: pointer;
  color: var(--gray-100);
}

.blade-header__close:hover {
  background: var(--gray-20);
}

/* Body */
.blade-body {
  flex: 1;
  overflow-x: hidden;
  overflow-y: auto;
  background: var(--gray-0);
  padding: 24px 0;
}

.blade-content {
  display: flex;
  flex-direction: column;
  gap: 24px;
  width: 100%;
  max-width: 100%;
  min-height: 100%;
}

/* Hero Section */
.blade-hero {
  display: flex;
  flex-direction: column;
  gap: 8px;
  padding: 0 24px;
}

.blade-hero__title {
  font-family: 'Inter', sans-serif;
  font-weight: 600;
  font-size: 22.781px;
  line-height: 1.3;
  color: #000000;
  margin: 0;
}

.blade-hero__description {
  font-family: 'Inter', sans-serif;
  font-weight: 400;
  font-size: 14.222px;
  line-height: 1.5;
  color: var(--gray-70);
  margin: 0;
}

/* Tabs */
.blade-tabs {
  display: flex;
  flex-direction: column;
  height: 37px;
}

.blade-tabs__links {
  display: flex;
  gap: 40px;
  padding: 0 24px;
  border-bottom: 1px solid var(--gray-40);
}

.blade-tabs__link {
  display: flex;
  flex-direction: column;
  gap: 4px;
  height: 36px;
  justify-content: flex-end;
  padding: 0 0 4px 0;
  background: none;
  border: none;
  cursor: pointer;
  font-family: 'Inter', sans-serif;
  font-size: 16px;
  line-height: 1.35;
  color: var(--gray-110);
  position: relative;
}

.blade-tabs__link--active {
  font-weight: 600;
}

.blade-tabs__link--active::after {
  content: '';
  position: absolute;
  bottom: -1px;
  left: 0;
  right: 0;
  height: 2px;
  background: var(--gray-110);
}

.blade-tabs__link:not(.blade-tabs__link--active) {
  font-weight: 400;
}

/* Tab Content */
.blade-tab-content {
  display: flex;
  flex-direction: column;
  gap: 24px;
  flex: 1;
  min-height: 0;
  width: 100%;
}

/* Sections */
.blade-section {
  display: flex;
  flex-direction: column;
  gap: 4px;
  padding: 0 24px;
  width: 100%;
  box-sizing: border-box;
}

.blade-section > * {
  margin: 0;
  max-width: 100%;
  box-sizing: border-box;
}

.blade-section:first-child {
  gap: 8px;
}

.blade-section--bottom {
  margin-top: auto;
}

.blade-label {
  font-family: 'Inter', sans-serif;
  font-weight: 600;
  font-size: 14.222px;
  line-height: 1.5;
  color: #2a2c35;
  margin: 0;
}

h4.blade-label {
  font-size: 16px;
}

.blade-sublabel {
  font-family: 'Inter', sans-serif;
  font-weight: 600;
  font-size: 14.222px;
  line-height: 1.5;
  color: #2a2c35;
  margin: 0;
}

.blade-helper {
  font-family: 'Inter', sans-serif;
  font-weight: 400;
  font-size: 14.222px;
  line-height: 1.5;
  color: #2a2c35;
  margin: 0;
}

.blade-section-header {
  display: flex;
  flex-direction: column;
  gap: 8px;
  margin-bottom: 16px;
}

.blade-field-group {
  display: flex;
  flex-direction: column;
  gap: 4px;
  margin-bottom: 12px;
}

.blade-field-label {
  font-family: 'Inter', sans-serif;
  font-weight: 600;
  font-size: 14.222px;
  line-height: 1.35;
  color: #2a2c35;
  margin: 0;
}

.blade-placeholder {
  font-family: 'Inter', sans-serif;
  font-size: 14.222px;
  color: var(--gray-70);
  padding: 0 24px;
}

/* Button Group */
.blade-button-group {
  display: flex;
  height: 36px;
  width: 100%;
  max-width: none;
}

.blade-button-group__item {
  flex: 1 1 0%;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 8px 12px;
  background: var(--gray-0);
  border: 1px solid var(--gray-40);
  font-family: 'Inter', sans-serif;
  font-size: 14.222px;
  line-height: 1.5;
  color: var(--gray-100);
  cursor: pointer;
  transition: all 0.2s;
  min-width: 0;
}

.blade-button-group__item:first-child {
  border-top-left-radius: 6px;
  border-bottom-left-radius: 6px;
}

.blade-button-group__item:last-child {
  border-top-right-radius: 6px;
  border-bottom-right-radius: 6px;
}

.blade-button-group__item:not(:first-child) {
  border-left: none;
}

.blade-button-group__item--active {
  background: rgba(18, 130, 151, 0.08);
  border: 1px solid var(--gray-40);
  font-weight: 600;
  color: var(--teal-90);
  z-index: 1;
}

/* Row Layout */
.blade-row {
  display: flex;
  gap: 8px;
  width: 100%;
  max-width: none;
  flex-wrap: nowrap;
  box-sizing: border-box;
}

.blade-field {
  flex: 1 1 0%;
  display: flex;
  flex-direction: column;
  gap: 4px;
  min-width: 0;
  max-width: none;
  box-sizing: border-box;
}

.blade-field__label {
  font-family: 'Inter', sans-serif;
  font-weight: 600;
  font-size: 14.222px;
  line-height: 1.5;
  color: var(--gray-100);
}

.blade-field :deep(.pendo-select) {
  width: 100% !important;
  max-width: none !important;
  display: block !important;
  min-width: 0 !important;
}

.blade-field :deep(.pendo-select__trigger) {
  width: 100% !important;
  max-width: none !important;
  min-width: 0 !important;
}

.blade-field :deep(.pendo-input) {
  width: 100% !important;
  max-width: none !important;
  min-width: 0 !important;
}

.blade-section :deep(.pendo-select) {
  width: 100% !important;
  max-width: none !important;
  display: block !important;
  min-width: 0 !important;
}

.blade-section :deep(.pendo-select__trigger) {
  width: 100% !important;
  max-width: none !important;
  min-width: 0 !important;
}

.blade-section :deep(.pendo-input) {
  width: 100% !important;
  max-width: none !important;
  min-width: 0 !important;
}

/* Channel Select */
.blade-channel-wrapper {
  position: relative;
  width: 100%;
}

.blade-channel-select {
  display: flex;
  align-items: center;
  justify-content: space-between;
  width: 100%;
  min-height: 36px;
  padding: 8px 12px;
  background: white;
  border: 1px solid #dadce5;
  border-radius: 6px;
  cursor: pointer;
  transition: border-color 0.15s ease, box-shadow 0.15s ease;
  outline: none;
}

.blade-channel-select:has(.blade-channel-tags) {
  padding: 4px 12px 4px 8px;
}

.blade-channel-select:not(:has(.blade-channel-tags)) {
  height: 36px;
  padding: 0 12px;
}

.blade-channel-select:hover {
  border-color: #2a2c35;
}

.blade-channel-select:focus {
  border-color: #2a2c35;
  box-shadow: 0 0 0 2px rgba(42, 44, 53, 0.15);
}

.blade-channel-select__placeholder {
  font-family: 'Inter', sans-serif;
  font-size: 14px;
  line-height: 1.5;
  color: #2a2c35;
}

.blade-channel-tags {
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
  flex: 1;
}

.blade-tag {
  display: flex;
  align-items: center;
  gap: 4px;
  padding: 4px 8px;
  background: var(--gray-30);
  border: 1px solid var(--gray-30);
  border-radius: 3px;
  flex-shrink: 1;
  min-width: 0;
}

.context-attachments-row .blade-tag {
  flex-shrink: 0;
}

.context-attachments-row .blade-tag--truncate {
  flex-shrink: 1;
  min-width: 0;
  max-width: 50%;
}

.blade-tag--truncate .blade-tag__text {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.blade-tag--counter {
  cursor: default;
  flex-shrink: 0;
}

.blade-tag__text {
  font-family: 'Inter', sans-serif;
  font-size: 12.642px;
  line-height: 1.5;
  color: var(--gray-110);
  font-weight: 600;
}

.blade-tag__close {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 0;
  background: none;
  border: none;
  cursor: pointer;
  color: var(--gray-100);
  flex-shrink: 0;
}

.blade-channel-select__icon {
  display: flex;
  align-items: center;
  justify-content: center;
  color: #6a6c75;
  flex-shrink: 0;
  margin-left: 8px;
  transition: transform 0.2s ease;
}

.blade-channel-select__icon--open {
  transform: rotate(180deg);
}

/* Channel Dropdown */
.blade-channel-dropdown {
  position: absolute;
  top: 100%;
  left: 0;
  right: 0;
  margin-top: 4px;
  background: white;
  border: 1px solid #dadce5;
  border-radius: 6px;
  box-shadow: 0 4px 12px rgba(0, 81, 100, 0.08);
  max-height: 164px;
  overflow-y: auto;
  z-index: 100;
}

.blade-channel-dropdown__item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 10px 12px;
  cursor: pointer;
  font-family: 'Inter', sans-serif;
  font-size: 14px;
  color: #2a2c35;
  transition: background-color 0.1s ease;
}

.blade-channel-dropdown__item:hover {
  background-color: #f5f6f8;
}

.blade-channel-dropdown__item:first-child {
  border-top-left-radius: 6px;
  border-top-right-radius: 6px;
}

.blade-channel-dropdown__item:last-child {
  border-bottom-left-radius: 6px;
  border-bottom-right-radius: 6px;
}

/* Channel Dropdown Transition */
.channel-dropdown-enter-active,
.channel-dropdown-leave-active {
  transition: opacity 0.15s ease, transform 0.15s ease;
}

.channel-dropdown-enter-from,
.channel-dropdown-leave-to {
  opacity: 0;
  transform: translateY(-8px);
}

/* Test Row */
.blade-test-row {
  display: flex;
  gap: 16px;
  align-items: center;
  width: 100%;
}

.blade-test-select {
  flex: 1;
  min-width: 0;
}

.blade-test-select :deep(.pendo-select) {
  width: 100% !important;
  display: block !important;
}

.blade-test-select :deep(.pendo-select__trigger) {
  justify-content: flex-start;
  gap: 12px;
  width: 100% !important;
}

.blade-test-select :deep(.pendo-select__placeholder) {
  color: #2a2c35;
}

.blade-test-select :deep(.pendo-select__arrow) {
  margin-left: auto;
}

.blade-test-select :deep(.pendo-select__dropdown) {
  max-height: 164px !important;
}

.blade-test-row :deep(.pendo-button) {
  flex-shrink: 0;
}

/* Footer */
.blade-footer {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 16px 20px 16px 24px;
  border-top: 1px solid var(--gray-40);
  background: var(--gray-0);
}

.blade-footer__actions {
  display: flex;
  gap: 8px;
  width: 100%;
}

.blade-footer__actions :deep(.pendo-button) {
  flex: 1;
  min-height: 36px;
}

/* Context Tab Styles */
.blade-tab-content .context-tracking-section {
  gap: 8px;
  display: flex;
  flex-direction: column;
  flex: 0 0 auto;
  min-height: 0;
  overflow: visible;
}

.context-tracking-header {
  display: flex;
  flex-direction: column;
  gap: 4px;
  flex-shrink: 0;
}

.blade-tab-content:has(.context-tracking-section) {
  flex: 1;
  min-height: 0;
  padding-bottom: 24px;
  overflow: visible;
}

.blade-content:has(.context-tracking-section) {
  display: flex;
  flex-direction: column;
  height: 100%;
  min-height: 0;
  overflow: visible;
}

/* Adjust context textarea section height when blade is narrower */
@media (min-width: 1025px) and (max-width: 1280px) {
  .blade-tab-content .context-tracking-section {
    overflow-y: auto;
  }
}

/* Input Container - Outer wrapper with border */
.context-input-container {
  display: flex;
  flex-direction: column;
  width: 100%;
  flex: 0 0 auto;
  min-height: 0;
  max-height: none;
  border: 1px solid var(--gray-40);
  border-radius: 6px;
  overflow: hidden;
  box-sizing: border-box;
}

.context-input-container--edit {
  border-color: #01586a;
}

/* Textarea Wrapper */
.context-textarea-wrapper {
  display: flex;
  flex-direction: column;
  flex: 0 0 auto;
  min-height: 0;
  gap: 4px;
  background: white;
  padding: 9px 4px 8px 8px;
  border-top-left-radius: 6px;
  border-top-right-radius: 6px;
  box-sizing: border-box;
  overflow: hidden;
}

/* Textarea itself */
.context-textarea {
  width: 100%;
  flex: 0 1 auto;
  height: auto;
  min-height: 165px;
  padding: 0 12px 4px 0;
  font-family: 'Inter', sans-serif;
  font-size: 14.222px;
  line-height: 1.5;
  color: var(--gray-100);
  background: transparent;
  border: none;
  resize: none;
  outline: none;
  overflow-y: auto;
  box-sizing: border-box;
}

.context-textarea:read-only {
  cursor: default;
}

/* Attachments Row */
.context-attachments-row {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 10px 8px 8px;
  min-height: 48px;
  flex-shrink: 0;
  background: white;
  border-top: 1px solid var(--gray-20);
  box-sizing: border-box;
}

.context-attachments-label {
  font-family: 'Inter', sans-serif;
  font-size: 14.222px;
  line-height: 1.5;
  color: var(--gray-100);
  flex-shrink: 0;
  white-space: nowrap;
}

/* Add Attachment Button Row */
.context-add-attachment-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 8px 10px 8px 8px;
  min-height: 48px;
  flex-shrink: 0;
  border-top: 1px solid var(--gray-40);
  border-bottom-left-radius: 6px;
  border-bottom-right-radius: 6px;
  box-sizing: border-box;
  background: white;
}

.context-edit-icons {
  display: flex;
  gap: 12px;
  align-items: center;
}

.context-edit-icon {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 0;
  background: none;
  border: none;
  cursor: pointer;
  color: var(--gray-70);
  transition: color 0.2s;
}

.context-edit-icon:hover {
  color: var(--gray-100);
}

.hidden {
  display: none;
}

.blade-tag__icon {
  flex-shrink: 0;
  color: var(--gray-100);
}

/* Subscription Card (Success State) */
.subscription-card {
  display: flex;
  flex-direction: column;
  gap: 8px;
  padding: 16px;
  border: 1px solid #eaecf1;
  border-radius: 3px;
  background: white;
}

.subscription-card__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.subscription-card__title {
  font-family: 'Inter', sans-serif;
  font-size: 14.222px;
  font-weight: 600;
  line-height: 1.35;
  color: #2a2c35;
  margin: 0;
}

.subscription-card__menu {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 20px;
  height: 20px;
  padding: 0;
  background: none;
  border: none;
  border-radius: 3px;
  cursor: pointer;
  color: var(--gray-100);
  transition: background-color 0.2s;
}

.subscription-card__menu:hover {
  background: var(--gray-20);
}

.subscription-card__details {
  font-family: 'Inter', sans-serif;
  font-size: 14.222px;
  font-weight: 400;
  line-height: 1.5;
  color: var(--gray-70);
  margin: 0;
}

.subscription-card__status {
  display: flex;
  align-items: center;
  gap: 8px;
}

.status-indicator {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  flex-shrink: 0;
}

.status-indicator--active {
  background: #00a86b;
}

.status-indicator--inactive {
  background: #9b9da5;
}

.status-text {
  font-family: 'Inter', sans-serif;
  font-size: 14.222px;
  font-weight: 400;
  line-height: 1.5;
  color: var(--gray-100);
}

.blade-footer__actions--success {
  justify-content: flex-start;
}

/* Adjust gap when blade is narrower (400px) - between 1025px and 1280px */
@media (min-width: 1025px) and (max-width: 1280px) {
  .blade-row {
    gap: 8px;
  }
  
  .blade-test-row {
    gap: 8px;
  }
}

/* Responsive - Stack on smaller widths */
@media (max-width: 768px) {
  .blade-wrapper {
    width: 100%;
  }

  .blade-row {
    flex-direction: column;
    gap: 16px;
  }

  .blade-test-row {
    flex-direction: column;
  }

  .blade-test-row > * {
    width: 100%;
  }
}
</style>
